# Generated by Django 2.2.16 on 2022-01-10 18:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0012_auto_20220110_2044'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='follow',
            name='unique-in-follow',
        ),
    ]
