# Generated by Django 2.2.16 on 2022-01-11 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0015_auto_20220110_2116'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='follow',
            constraint=models.UniqueConstraint(fields=('user_id', 'author_id'), name='unique following'),
        ),
    ]
